documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'

cli:
  - changed-files:
      - any-glob-to-any-file: 'src/aydin/cli/**'

gui:
  - changed-files:
      - any-glob-to-any-file: 'src/aydin/gui/**'

tests:
  - changed-files:
      - any-glob-to-any-file: '**/tests/**'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
