ignore:
  - "aydin/**/demo/**"
  - "aydin/**/test/**"
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%
comment:
  require_changes: false
